_wandb:
    value:
        cli_version: 0.23.1
        e:
            bcbbzmcq2f0dom6xysr7rdkkwm79b7zj:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "510989955072"
                        used: "260706295808"
                email: kokrhui.ong@gmail.com
                executable: C:\Users\HP\Documents\repos\mlops-weights-&-biases\venv\Scripts\python.exe
                git:
                    commit: 4299b398ba0805af710f510a4dcc8aacf7852c5d
                    remote: https://github.com/ONGKOKRHUI/mlops-weights---biases-mlflow.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-c572972b-5d64-d032-47e1-06a715da7990
                host: LAPTOP-1TMQC35K
                memory:
                    total: "16390750208"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\HP\Documents\repos\mlops-weights-&-biases\main.py
                python: CPython 3.13.9
                root: C:\Users\HP\Documents\repos\mlops-weights-&-biases
                startedAt: "2025-12-31T04:17:39.682390Z"
                writerId: bcbbzmcq2f0dom6xysr7rdkkwm79b7zj
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.13.9
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
architecture:
    value: CNN
batch_size:
    value: 128
classes:
    value: 10
dataset:
    value: MNIST
db_path:
    value: mnist.db
epochs:
    value: 5
kernels:
    value:
        - 16
        - 32
learning_rate:
    value: 0.005
