wandb_version: 1

architecture:
  value: CNN
batch_size:
  value: 256
classes:
  value: 10
dataset:
  value: MNIST
dataset_artifact:
  value: mnist-sqlite-data:latest
db_path:
  value: data/mnist.db
epochs:
  value: 3
kernels:
  value:
  - 16
  - 32
learning_rate:
  value: 0.008052426270506263
model_path:
  value: model/mnist.onnx
