_wandb:
    value:
        cli_version: 0.23.1
        e:
            xelwn4jkh432ztsn5xwiomor1roi2s1f:
                codePath: c:\Users\HP\Documents\repos\mlops-weights-&-biases\wandb.ipynb
                codePathLocal: wandb.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "510989955072"
                        used: "260710416384"
                email: kokrhui.ong@gmail.com
                executable: c:\Users\HP\Documents\repos\mlops-weights-&-biases\venv\Scripts\python.exe
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-c572972b-5d64-d032-47e1-06a715da7990
                host: LAPTOP-1TMQC35K
                memory:
                    total: "16390750208"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\HP\Documents\repos\mlops-weights-&-biases\wandb.ipynb
                python: CPython 3.13.9
                root: c:\Users\HP\Documents\repos\mlops-weights-&-biases
                startedAt: "2025-12-30T05:46:43.221080Z"
                writerId: xelwn4jkh432ztsn5xwiomor1roi2s1f
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 2
                - 16
                - 61
            "4": 3.13.9
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
architecture:
    value: CNN
batch_size:
    value: 128
classes:
    value: 10
dataset:
    value: MNIST
epochs:
    value: 5
kernels:
    value:
        - 16
        - 32
learning_rate:
    value: 0.005
