_wandb:
    value:
        cli_version: 0.23.1
        e:
            couij6gsgvfpnm9bfxecpikrqui2z85l:
                codePath: c:\Users\HP\Documents\repos\mlops-weights-&-biases\test.ipynb
                codePathLocal: test.ipynb
                email: kokrhui.ong@gmail.com
                executable: c:\Users\HP\Documents\repos\mlops-weights-&-biases\venv\Scripts\python.exe
                host: LAPTOP-1TMQC35K
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\HP\Documents\repos\mlops-weights-&-biases\test.ipynb
                python: CPython 3.13.9
                root: c:\Users\HP\Documents\repos\mlops-weights-&-biases
                startedAt: "2025-12-29T08:07:47.233832Z"
                writerId: couij6gsgvfpnm9bfxecpikrqui2z85l
        m: []
        python_version: 3.13.9
        t:
            "3":
                - 2
                - 16
            "4": 3.13.9
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
epochs:
    value: 10
lr:
    value: 0.01
