_wandb:
    value:
        cli_version: 0.23.1
        e:
            6puyfinevpqi4nscmdgbjn1cv7m2he47:
                codePath: sweep.py
                codePathLocal: sweep.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "510989955072"
                        used: "261941776384"
                email: kokrhui.ong@gmail.com
                executable: C:\Users\HP\Documents\repos\mlops-weights-&-biases\venv\Scripts\python.exe
                git:
                    commit: fa1802831d82c23380a9145bffecb72f7a5a9db2
                    remote: https://github.com/ONGKOKRHUI/mlops-weights---biases-mlflow.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-c572972b-5d64-d032-47e1-06a715da7990
                host: LAPTOP-1TMQC35K
                memory:
                    total: "16390750208"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\HP\Documents\repos\mlops-weights-&-biases\sweep.py
                python: CPython 3.13.9
                root: C:\Users\HP\Documents\repos\mlops-weights-&-biases
                startedAt: "2026-01-02T02:04:17.478573Z"
                writerId: 6puyfinevpqi4nscmdgbjn1cv7m2he47
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 1
                - 2
                - 14
                - 61
                - 62
            "4": 3.13.9
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
architecture:
    value: CNN
batch_size:
    value: 256
classes:
    value: 10
dataset:
    value: MNIST
dataset_artifact:
    value: mnist-sqlite-data:latest
db_path:
    value: data/mnist.db
epochs:
    value: 3
kernels:
    value:
        - 16
        - 32
learning_rate:
    value: 0.009563424321620358
model_path:
    value: model/mnist.onnx
